# Generated by Django 2.2 on 2019-04-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
