# Generated by Django 2.2 on 2019-04-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.TextField(blank=True),
        ),
    ]
